# This file was generated by stellar_contract_bindings v0.5.0b0 and stellar_sdk v13.2.0.

from __future__ import annotations

from enum import IntEnum, Enum
from typing import Dict, List, Tuple, Optional, Union

from stellar_sdk import scval, xdr, Address, MuxedAccount, Keypair
from stellar_sdk.contract import AssembledTransaction, ContractClient
from stellar_sdk.contract import AssembledTransactionAsync, ContractClientAsync

NULL_ACCOUNT = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF"


class AppKindKind(Enum):
    Inkternity = "Inkternity"
    Andromica = "Andromica"
    Pintheon = "Pintheon"
    Other = "Other"


class AppKind:
    def __init__(
        self,
        kind: AppKindKind,
    ):
        self.kind = kind

    def to_scval(self) -> xdr.SCVal:
        if self.kind == AppKindKind.Inkternity:
            return scval.to_enum(self.kind.name, None)
        if self.kind == AppKindKind.Andromica:
            return scval.to_enum(self.kind.name, None)
        if self.kind == AppKindKind.Pintheon:
            return scval.to_enum(self.kind.name, None)
        if self.kind == AppKindKind.Other:
            return scval.to_enum(self.kind.name, None)
        raise ValueError(f"Invalid kind: {self.kind}")

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_enum(val)
        kind = AppKindKind(elements[0])
        if kind == AppKindKind.Inkternity:
            return cls(kind)
        if kind == AppKindKind.Andromica:
            return cls(kind)
        if kind == AppKindKind.Pintheon:
            return cls(kind)
        if kind == AppKindKind.Other:
            return cls(kind)
        raise ValueError(f"Invalid kind: {kind}")

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, AppKind):
            return NotImplemented
        if self.kind != other.kind:
            return False
        return True

    def __hash__(self) -> int:
        return hash(self.kind)


class CertStatusKind(Enum):
    Active = "Active"
    Revoked = "Revoked"
    Expired = "Expired"


class CertStatus:
    def __init__(
        self,
        kind: CertStatusKind,
    ):
        self.kind = kind

    def to_scval(self) -> xdr.SCVal:
        if self.kind == CertStatusKind.Active:
            return scval.to_enum(self.kind.name, None)
        if self.kind == CertStatusKind.Revoked:
            return scval.to_enum(self.kind.name, None)
        if self.kind == CertStatusKind.Expired:
            return scval.to_enum(self.kind.name, None)
        raise ValueError(f"Invalid kind: {self.kind}")

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_enum(val)
        kind = CertStatusKind(elements[0])
        if kind == CertStatusKind.Active:
            return cls(kind)
        if kind == CertStatusKind.Revoked:
            return cls(kind)
        if kind == CertStatusKind.Expired:
            return cls(kind)
        raise ValueError(f"Invalid kind: {kind}")

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, CertStatus):
            return NotImplemented
        if self.kind != other.kind:
            return False
        return True

    def __hash__(self) -> int:
        return hash(self.kind)


class DataKeyKind(Enum):
    AppCa = "AppCa"
    AppsByMember = "AppsByMember"
    AllApps = "AllApps"


class DataKey:
    def __init__(
        self,
        kind: DataKeyKind,
        app_ca: Optional[Union[Address, str]] = None,
        apps_by_member: Optional[bytes] = None,
    ):
        self.kind = kind
        self.app_ca = app_ca
        self.apps_by_member = apps_by_member

    def to_scval(self) -> xdr.SCVal:
        if self.kind == DataKeyKind.AppCa:
            assert self.app_ca is not None
            return scval.to_enum(self.kind.name, scval.to_address(self.app_ca))
        if self.kind == DataKeyKind.AppsByMember:
            assert self.apps_by_member is not None
            return scval.to_enum(self.kind.name, scval.to_bytes(self.apps_by_member))
        if self.kind == DataKeyKind.AllApps:
            return scval.to_enum(self.kind.name, None)
        raise ValueError(f"Invalid kind: {self.kind}")

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_enum(val)
        kind = DataKeyKind(elements[0])
        if kind == DataKeyKind.AppCa:
            assert elements[1] is not None and isinstance(elements[1], xdr.SCVal)
            return cls(kind, app_ca=scval.from_address(elements[1]))
        if kind == DataKeyKind.AppsByMember:
            assert elements[1] is not None and isinstance(elements[1], xdr.SCVal)
            return cls(kind, apps_by_member=scval.from_bytes(elements[1]))
        if kind == DataKeyKind.AllApps:
            return cls(kind)
        raise ValueError(f"Invalid kind: {kind}")

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, DataKey):
            return NotImplemented
        if self.kind != other.kind:
            return False
        if self.kind == DataKeyKind.AppCa:
            return self.app_ca == other.app_ca
        if self.kind == DataKeyKind.AppsByMember:
            return self.apps_by_member == other.apps_by_member
        return True

    def __hash__(self) -> int:
        if self.kind == DataKeyKind.AppCa:
            return hash((self.kind, self.app_ca))
        if self.kind == DataKeyKind.AppsByMember:
            return hash((self.kind, self.apps_by_member))
        return hash(self.kind)


class AppCaRecord:
    app_address: Address
    app_kind: AppKind
    expires_at: int
    fingerprint: bytes
    issued_at: int
    member_pubkey: bytes
    pubkey_alg: bytes
    serial: int
    status: CertStatus
    updated_at: int

    def __init__(
        self,
        app_address: Union[Address, str],
        app_kind: AppKind,
        expires_at: int,
        fingerprint: bytes,
        issued_at: int,
        member_pubkey: bytes,
        pubkey_alg: bytes,
        serial: int,
        status: CertStatus,
        updated_at: int,
    ):
        self.app_address = app_address
        self.app_kind = app_kind
        self.expires_at = expires_at
        self.fingerprint = fingerprint
        self.issued_at = issued_at
        self.member_pubkey = member_pubkey
        self.pubkey_alg = pubkey_alg
        self.serial = serial
        self.status = status
        self.updated_at = updated_at

    def to_scval(self) -> xdr.SCVal:
        return scval.to_struct(
            {
                "app_address": scval.to_address(self.app_address),
                "app_kind": self.app_kind.to_scval(),
                "expires_at": scval.to_uint64(self.expires_at),
                "fingerprint": scval.to_bytes(self.fingerprint),
                "issued_at": scval.to_uint64(self.issued_at),
                "member_pubkey": scval.to_bytes(self.member_pubkey),
                "pubkey_alg": scval.to_string(self.pubkey_alg),
                "serial": scval.to_uint32(self.serial),
                "status": self.status.to_scval(),
                "updated_at": scval.to_uint64(self.updated_at),
            }
        )

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_struct(val)
        return cls(
            scval.from_address(elements["app_address"]),
            AppKind.from_scval(elements["app_kind"]),
            scval.from_uint64(elements["expires_at"]),
            scval.from_bytes(elements["fingerprint"]),
            scval.from_uint64(elements["issued_at"]),
            scval.from_bytes(elements["member_pubkey"]),
            scval.from_string(elements["pubkey_alg"]),
            scval.from_uint32(elements["serial"]),
            CertStatus.from_scval(elements["status"]),
            scval.from_uint64(elements["updated_at"]),
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, AppCaRecord):
            return NotImplemented
        return (
            self.app_address == other.app_address
            and self.app_kind == other.app_kind
            and self.expires_at == other.expires_at
            and self.fingerprint == other.fingerprint
            and self.issued_at == other.issued_at
            and self.member_pubkey == other.member_pubkey
            and self.pubkey_alg == other.pubkey_alg
            and self.serial == other.serial
            and self.status == other.status
            and self.updated_at == other.updated_at
        )

    def __hash__(self) -> int:
        return hash(
            (
                self.app_address,
                self.app_kind,
                self.expires_at,
                self.fingerprint,
                self.issued_at,
                self.member_pubkey,
                self.pubkey_alg,
                self.serial,
                self.status,
                self.updated_at,
            )
        )


class RegisterEvent:
    app_address: Address
    app_kind: AppKind
    expires_at: int
    fingerprint: bytes
    member_pubkey: bytes

    def __init__(
        self,
        app_address: Union[Address, str],
        app_kind: AppKind,
        expires_at: int,
        fingerprint: bytes,
        member_pubkey: bytes,
    ):
        self.app_address = app_address
        self.app_kind = app_kind
        self.expires_at = expires_at
        self.fingerprint = fingerprint
        self.member_pubkey = member_pubkey

    def to_scval(self) -> xdr.SCVal:
        return scval.to_struct(
            {
                "app_address": scval.to_address(self.app_address),
                "app_kind": self.app_kind.to_scval(),
                "expires_at": scval.to_uint64(self.expires_at),
                "fingerprint": scval.to_bytes(self.fingerprint),
                "member_pubkey": scval.to_bytes(self.member_pubkey),
            }
        )

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_struct(val)
        return cls(
            scval.from_address(elements["app_address"]),
            AppKind.from_scval(elements["app_kind"]),
            scval.from_uint64(elements["expires_at"]),
            scval.from_bytes(elements["fingerprint"]),
            scval.from_bytes(elements["member_pubkey"]),
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, RegisterEvent):
            return NotImplemented
        return (
            self.app_address == other.app_address
            and self.app_kind == other.app_kind
            and self.expires_at == other.expires_at
            and self.fingerprint == other.fingerprint
            and self.member_pubkey == other.member_pubkey
        )

    def __hash__(self) -> int:
        return hash(
            (
                self.app_address,
                self.app_kind,
                self.expires_at,
                self.fingerprint,
                self.member_pubkey,
            )
        )


class RotateEvent:
    app_address: Address
    new_expires_at: int
    new_fingerprint: bytes
    serial: int

    def __init__(
        self,
        app_address: Union[Address, str],
        new_expires_at: int,
        new_fingerprint: bytes,
        serial: int,
    ):
        self.app_address = app_address
        self.new_expires_at = new_expires_at
        self.new_fingerprint = new_fingerprint
        self.serial = serial

    def to_scval(self) -> xdr.SCVal:
        return scval.to_struct(
            {
                "app_address": scval.to_address(self.app_address),
                "new_expires_at": scval.to_uint64(self.new_expires_at),
                "new_fingerprint": scval.to_bytes(self.new_fingerprint),
                "serial": scval.to_uint32(self.serial),
            }
        )

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_struct(val)
        return cls(
            scval.from_address(elements["app_address"]),
            scval.from_uint64(elements["new_expires_at"]),
            scval.from_bytes(elements["new_fingerprint"]),
            scval.from_uint32(elements["serial"]),
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, RotateEvent):
            return NotImplemented
        return (
            self.app_address == other.app_address
            and self.new_expires_at == other.new_expires_at
            and self.new_fingerprint == other.new_fingerprint
            and self.serial == other.serial
        )

    def __hash__(self) -> int:
        return hash(
            (self.app_address, self.new_expires_at, self.new_fingerprint, self.serial)
        )


class RevokeEvent:
    app_address: Address
    by_app: bool

    def __init__(self, app_address: Union[Address, str], by_app: bool):
        self.app_address = app_address
        self.by_app = by_app

    def to_scval(self) -> xdr.SCVal:
        return scval.to_struct(
            {
                "app_address": scval.to_address(self.app_address),
                "by_app": scval.to_bool(self.by_app),
            }
        )

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_struct(val)
        return cls(
            scval.from_address(elements["app_address"]),
            scval.from_bool(elements["by_app"]),
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, RevokeEvent):
            return NotImplemented
        return self.app_address == other.app_address and self.by_app == other.by_app

    def __hash__(self) -> int:
        return hash((self.app_address, self.by_app))


class Client(ContractClient):
    def register_app_ca(
        self,
        app_address: Union[Address, str],
        member_pubkey: bytes,
        app_kind: AppKind,
        fingerprint: bytes,
        pubkey_alg: bytes,
        expires_at: int,
        nonce: int,
        auth_payload: bytes,
        auth_signature: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[None]:
        return self.invoke(
            "register_app_ca",
            [
                scval.to_address(app_address),
                scval.to_bytes(member_pubkey),
                app_kind.to_scval(),
                scval.to_bytes(fingerprint),
                scval.to_string(pubkey_alg),
                scval.to_uint64(expires_at),
                scval.to_uint64(nonce),
                scval.to_bytes(auth_payload),
                scval.to_bytes(auth_signature),
            ],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def rotate_app_ca(
        self,
        app_address: Union[Address, str],
        new_fingerprint: bytes,
        new_expires_at: int,
        nonce: int,
        auth_payload: bytes,
        auth_signature: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[None]:
        return self.invoke(
            "rotate_app_ca",
            [
                scval.to_address(app_address),
                scval.to_bytes(new_fingerprint),
                scval.to_uint64(new_expires_at),
                scval.to_uint64(nonce),
                scval.to_bytes(auth_payload),
                scval.to_bytes(auth_signature),
            ],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def revoke_by_app(
        self,
        app_address: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[None]:
        return self.invoke(
            "revoke_by_app",
            [scval.to_address(app_address)],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def revoke_by_member(
        self,
        app_address: Union[Address, str],
        nonce: int,
        auth_payload: bytes,
        auth_signature: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[None]:
        return self.invoke(
            "revoke_by_member",
            [
                scval.to_address(app_address),
                scval.to_uint64(nonce),
                scval.to_bytes(auth_payload),
                scval.to_bytes(auth_signature),
            ],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def get_app_ca(
        self,
        app_address: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[Optional[AppCaRecord]]:
        """Returns the stored record if present. The returned `status` is
        transitioned `Active -> Expired` at view time if `expires_at <= now`,
        so callers don't need to recompute. Storage is not mutated."""
        return self.invoke(
            "get_app_ca",
            [scval.to_address(app_address)],
            parse_result_xdr_fn=lambda v: (
                AppCaRecord.from_scval(v)
                if v.type != xdr.SCValType.SCV_VOID
                else scval.from_void(v)
            ),
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def is_trusted(
        self,
        app_address: Union[Address, str],
        fingerprint: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[bool]:
        """Fast trust check used by C2PA verifiers. True iff record exists,
        stored status is `Active`, `now < expires_at`, and fingerprint matches."""
        return self.invoke(
            "is_trusted",
            [scval.to_address(app_address), scval.to_bytes(fingerprint)],
            parse_result_xdr_fn=lambda v: scval.from_bool(v),
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def apps_of_member(
        self,
        member_pubkey: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[List[Address]]:
        """Every app address ever registered under `member_pubkey`, including
        revoked ones. Callers filter via `get_app_ca` for active-only."""
        return self.invoke(
            "apps_of_member",
            [scval.to_bytes(member_pubkey)],
            parse_result_xdr_fn=lambda v: [
                scval.from_address(e) for e in scval.from_vec(v)
            ],
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def list_active_apps(
        self,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[List[Address]]:
        """All registered apps whose stored status is `Active`. Does not filter
        by expiry — that requires per-record reads, which callers can do
        selectively via `is_trusted` or `get_app_ca`."""
        return self.invoke(
            "list_active_apps",
            [],
            parse_result_xdr_fn=lambda v: [
                scval.from_address(e) for e in scval.from_vec(v)
            ],
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )


class ClientAsync(ContractClientAsync):
    async def register_app_ca(
        self,
        app_address: Union[Address, str],
        member_pubkey: bytes,
        app_kind: AppKind,
        fingerprint: bytes,
        pubkey_alg: bytes,
        expires_at: int,
        nonce: int,
        auth_payload: bytes,
        auth_signature: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[None]:
        return await self.invoke(
            "register_app_ca",
            [
                scval.to_address(app_address),
                scval.to_bytes(member_pubkey),
                app_kind.to_scval(),
                scval.to_bytes(fingerprint),
                scval.to_string(pubkey_alg),
                scval.to_uint64(expires_at),
                scval.to_uint64(nonce),
                scval.to_bytes(auth_payload),
                scval.to_bytes(auth_signature),
            ],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def rotate_app_ca(
        self,
        app_address: Union[Address, str],
        new_fingerprint: bytes,
        new_expires_at: int,
        nonce: int,
        auth_payload: bytes,
        auth_signature: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[None]:
        return await self.invoke(
            "rotate_app_ca",
            [
                scval.to_address(app_address),
                scval.to_bytes(new_fingerprint),
                scval.to_uint64(new_expires_at),
                scval.to_uint64(nonce),
                scval.to_bytes(auth_payload),
                scval.to_bytes(auth_signature),
            ],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def revoke_by_app(
        self,
        app_address: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[None]:
        return await self.invoke(
            "revoke_by_app",
            [scval.to_address(app_address)],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def revoke_by_member(
        self,
        app_address: Union[Address, str],
        nonce: int,
        auth_payload: bytes,
        auth_signature: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[None]:
        return await self.invoke(
            "revoke_by_member",
            [
                scval.to_address(app_address),
                scval.to_uint64(nonce),
                scval.to_bytes(auth_payload),
                scval.to_bytes(auth_signature),
            ],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def get_app_ca(
        self,
        app_address: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[Optional[AppCaRecord]]:
        """Returns the stored record if present. The returned `status` is
        transitioned `Active -> Expired` at view time if `expires_at <= now`,
        so callers don't need to recompute. Storage is not mutated."""
        return await self.invoke(
            "get_app_ca",
            [scval.to_address(app_address)],
            parse_result_xdr_fn=lambda v: (
                AppCaRecord.from_scval(v)
                if v.type != xdr.SCValType.SCV_VOID
                else scval.from_void(v)
            ),
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def is_trusted(
        self,
        app_address: Union[Address, str],
        fingerprint: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[bool]:
        """Fast trust check used by C2PA verifiers. True iff record exists,
        stored status is `Active`, `now < expires_at`, and fingerprint matches."""
        return await self.invoke(
            "is_trusted",
            [scval.to_address(app_address), scval.to_bytes(fingerprint)],
            parse_result_xdr_fn=lambda v: scval.from_bool(v),
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def apps_of_member(
        self,
        member_pubkey: bytes,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[List[Address]]:
        """Every app address ever registered under `member_pubkey`, including
        revoked ones. Callers filter via `get_app_ca` for active-only."""
        return await self.invoke(
            "apps_of_member",
            [scval.to_bytes(member_pubkey)],
            parse_result_xdr_fn=lambda v: [
                scval.from_address(e) for e in scval.from_vec(v)
            ],
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def list_active_apps(
        self,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[List[Address]]:
        """All registered apps whose stored status is `Active`. Does not filter
        by expiry — that requires per-record reads, which callers can do
        selectively via `is_trusted` or `get_app_ca`."""
        return await self.invoke(
            "list_active_apps",
            [],
            parse_result_xdr_fn=lambda v: [
                scval.from_address(e) for e in scval.from_vec(v)
            ],
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )
