#!/usr/bin/env python3
"""
Automated Local Stellar RPC Node Setup using Docker

This script automates the setup of a local Stellar RPC node for reliable
Soroban contract deployment, avoiding public endpoint congestion.

Usage:
    python setup_local_stellar.py --network mainnet
    python setup_local_stellar.py --network testnet
    python setup_local_stellar.py --stop
    python setup_local_stellar.py --status
"""

import argparse
import json
import os
import subprocess
import sys
import time
import requests
from pathlib import Path
from typing import Dict, Optional, Tuple

# Constants
DOCKER_IMAGE = "stellar/soroban-rpc:latest"
CONTAINER_NAME_MAINNET = "soroban-rpc-mainnet"
CONTAINER_NAME_TESTNET = "soroban-rpc-testnet"
CONFIG_DIR = Path.home() / "soroban-rpc"
LOCAL_RPC_URL = "http://localhost:8000"

# Network configurations
NETWORK_CONFIGS = {
    "mainnet": {
        "passphrase": "Public Global Stellar Network ; September 2015",
        "history_archive": "https://history.stellar.org/prd/core-live/core_live_001",
        "container_name": CONTAINER_NAME_MAINNET
    },
    "testnet": {
        "passphrase": "Test SDF Network ; September 2015", 
        "history_archive": "https://history.stellar.org/prd/core-testnet/core_testnet_001",
        "container_name": CONTAINER_NAME_TESTNET
    }
}

def run_command(cmd: list, capture_output: bool = True, check: bool = True) -> subprocess.CompletedProcess:
    """Run a shell command and return the result."""
    try:
        result = subprocess.run(
            cmd, 
            capture_output=capture_output, 
            text=True, 
            check=check
        )
        return result
    except subprocess.CalledProcessError as e:
        print(f"❌ Command failed: {' '.join(cmd)}")
        print(f"   Error: {e.stderr}")
        raise

def check_docker_installation() -> bool:
    """Check if Docker is installed and running."""
    try:
        result = run_command(["docker", "--version"])
        print(f"✅ Docker found: {result.stdout.strip()}")
        
        # Check if Docker daemon is running
        run_command(["docker", "info"])
        print("✅ Docker daemon is running")
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("❌ Docker is not installed or not running")
        print("   Please install Docker: https://docs.docker.com/get-docker/")
        return False

def check_image_exists(image_name: str) -> bool:
    """Check if Docker image exists locally."""
    try:
        # Extract repository name without tag for more reliable checking
        repo_name = image_name.split(':')[0] if ':' in image_name else image_name
        
        result = run_command(["docker", "images", "--format", "{{.Repository}}:{{.Tag}}"])
        images = result.stdout.strip().split('\n') if result.stdout.strip() else []
        
        if image_name in images:
            print(f"✅ Docker image found: {image_name}")
            return True
        else:
            print(f"📥 Docker image not found: {image_name}")
            print(f"   Available images: {len([img for img in images if img])}")
            return False
    except subprocess.CalledProcessError as e:
        print(f"❌ Error checking images: {e}")
        return False

def pull_docker_image(image_name: str) -> bool:
    """Pull Docker image from registry."""
    try:
        print(f"📥 Pulling Docker image: {image_name}")
        print("   This may take a few minutes...")
        
        # Use subprocess.run without check to see progress
        process = subprocess.Popen(
            ["docker", "pull", image_name],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True
        )
        
        # Show progress
        for line in process.stdout:
            print(f"   {line.strip()}")
            
        process.wait()
        
        if process.returncode == 0:
            print(f"✅ Successfully pulled: {image_name}")
            return True
        else:
            print(f"❌ Failed to pull: {image_name}")
            return False
            
    except Exception as e:
        print(f"❌ Error pulling image: {e}")
        return False

def create_required_directories() -> bool:
    """Create required directories for configuration and data."""
    try:
        CONFIG_DIR.mkdir(exist_ok=True)
        print(f"✅ Config directory created: {CONFIG_DIR}")
        return True
    except Exception as e:
        print(f"❌ Failed to create directories: {e}")
        return False

def generate_stellar_config(network: str) -> bool:
    """Generate stellar-rpc.toml configuration file."""
    config_path = CONFIG_DIR / "stellar-rpc.toml"
    
    # Basic stellar-rpc.toml configuration
    config_content = f"""# Stellar RPC Configuration for {network}
# Generated by setup_local_stellar.py

ENDPOINT = "0.0.0.0:8000"
ADMIN_ENDPOINT = "0.0.0.0:8001"
NETWORK_PASSPHRASE = "{NETWORK_CONFIGS[network]['passphrase']}"
HISTORY_ARCHIVE_URLS = ["{NETWORK_CONFIGS[network]['history_archive']}"]
CAPTIVE_CORE_CONFIG_PATH = "/dev/null"

"""
    
    try:
        with open(config_path, 'w') as f:
            f.write(config_content)
        print(f"✅ Configuration generated: {config_path}")
        return True
    except Exception as e:
        print(f"❌ Failed to generate config: {e}")
        return False

def get_container_status(container_name: str) -> str:
    """Get the status of a Docker container."""
    try:
        result = run_command(["docker", "ps", "-a", "--filter", f"name={container_name}", "--format", "{{.Status}}"])
        if result.stdout.strip():
            return result.stdout.strip()
        else:
            return "not_found"
    except subprocess.CalledProcessError:
        return "error"

def start_stellar_container(network: str) -> bool:
    """Start Stellar RPC container for specified network."""
    container_name = NETWORK_CONFIGS[network]["container_name"]
    
    # Check if container already exists
    status = get_container_status(container_name)
    if status != "not_found":
        if "Up" in status:
            print(f"✅ Container already running: {container_name}")
            return True
        else:
            print(f"🔄 Removing existing container: {container_name}")
            run_command(["docker", "rm", container_name])
    
    # Generate config
    if not generate_stellar_config(network):
        return False
    
    # Start container with correct RPC config
    docker_cmd = [
        "docker", "run", "-d",
        "--name", container_name,
        "-p", "8000:8000",
        "-p", "8001:8001", 
        "-v", f"{CONFIG_DIR}:/config",
        "-v", "soroban-data:/var/lib/stellar",
        DOCKER_IMAGE,
        "--config-path=/config/stellar-rpc.toml",
        f"--network-passphrase={NETWORK_CONFIGS[network]['passphrase']}",
        f"--history-archive-urls={NETWORK_CONFIGS[network]['history_archive']}",
        "--admin-endpoint=0.0.0.0:8001",
        "--endpoint=0.0.0.0:8000"
    ]
    
    try:
        print(f"🚀 Starting {network} container...")
        result = run_command(docker_cmd)
        print(f"✅ Container started: {container_name}")
        print(f"   RPC URL: {LOCAL_RPC_URL}")
        print(f"   Admin URL: http://localhost:8001")
        return True
    except Exception as e:
        print(f"❌ Failed to start container: {e}")
        return False

def stop_stellar_container(container_name: Optional[str] = None) -> bool:
    """Stop Stellar RPC container."""
    if not container_name:
        # Stop both containers
        success = True
        for network in NETWORK_CONFIGS.keys():
            name = NETWORK_CONFIGS[network]["container_name"]
            if get_container_status(name) != "not_found":
                try:
                    print(f"🛑 Stopping container: {name}")
                    run_command(["docker", "stop", name])
                    run_command(["docker", "rm", name])
                    print(f"✅ Stopped: {name}")
                except Exception as e:
                    print(f"❌ Failed to stop {name}: {e}")
                    success = False
        return success
    else:
        # Stop specific container
        status = get_container_status(container_name)
        if status == "not_found":
            print(f"ℹ️  Container not found: {container_name}")
            return True
        
        try:
            print(f"🛑 Stopping container: {container_name}")
            run_command(["docker", "stop", container_name])
            run_command(["docker", "rm", container_name])
            print(f"✅ Stopped: {container_name}")
            return True
        except Exception as e:
            print(f"❌ Failed to stop container: {e}")
            return False

def get_node_health(rpc_url: str = LOCAL_RPC_URL) -> Dict:
    """Check the health of the Stellar RPC node."""
    try:
        response = requests.post(
            rpc_url,
            json={
                "jsonrpc": "2.0",
                "id": 1,
                "method": "getHealth"
            },
            timeout=10
        )
        
        if response.status_code == 200:
            data = response.json()
            if "result" in data:
                return {
                    "status": "healthy",
                    "response": data["result"]
                }
        
        return {"status": "unhealthy", "error": response.text}
    except Exception as e:
        return {"status": "error", "error": str(e)}

def check_sync_status(rpc_url: str = LOCAL_RPC_URL) -> Dict:
    """Check the sync status of the Stellar node."""
    try:
        response = requests.post(
            rpc_url,
            json={
                "jsonrpc": "2.0", 
                "id": 1,
                "method": "getLedgerInfo"
            },
            timeout=10
        )
        
        if response.status_code == 200:
            data = response.json()
            if "result" in data:
                result = data["result"]
                return {
                    "status": "syncing",
                    "ledger": result.get("sequence", 0),
                    "isSynced": result.get("isSynced", False),
                    "response": result
                }
        
        return {"status": "error", "error": response.text}
    except Exception as e:
        return {"status": "error", "error": str(e)}

def monitor_sync_progress(timeout: int = 3600) -> bool:
    """Monitor sync progress until node is fully synced."""
    print("📊 Monitoring sync progress...")
    print("   This can take up to 1 hour for initial sync")
    print("   Press Ctrl+C to stop monitoring")
    
    start_time = time.time()
    
    try:
        while time.time() - start_time < timeout:
            health = get_node_health()
            sync = check_sync_status()
            
            if health["status"] == "healthy" and sync.get("isSynced", False):
                print(f"✅ Node is fully synced!")
                print(f"   Current ledger: {sync.get('ledger', 'Unknown')}")
                return True
            
            # Show progress
            if sync["status"] == "syncing":
                elapsed = int(time.time() - start_time)
                ledger = sync.get("ledger", 0)
                print(f"   ⏳ Syncing... Ledger: {ledger:,} (elapsed: {elapsed}s)")
            
            time.sleep(30)  # Check every 30 seconds
            
    except KeyboardInterrupt:
        print("\n⚠️  Sync monitoring stopped by user")
        return False
    
    print(f"⚠️  Sync timeout after {timeout} seconds")
    return False

def update_deploy_script_rpc_url() -> bool:
    """Update deploy_contracts.py to use local RPC URL."""
    deploy_script = Path("deploy_contracts.py")
    
    if not deploy_script.exists():
        print("❌ deploy_contracts.py not found")
        return False
    
    try:
        # Read current content
        with open(deploy_script, 'r') as f:
            content = f.read()
        
        # Check if already updated
        if LOCAL_RPC_URL in content:
            print(f"✅ deploy_contracts.py already configured for local RPC")
            return True
        
        # Add local RPC URL configuration
        local_rpc_config = f'\n# Local RPC URL (set by setup_local_stellar.py)\nif os.environ.get("STELLAR_RPC_URL") is None:\n    os.environ["STELLAR_RPC_URL"] = "{LOCAL_RPC_URL}"\n'
        
        # Insert after imports
        import_end = content.find("from typing import Dict, List, Optional")
        if import_end == -1:
            print("❌ Could not find import section in deploy_contracts.py")
            return False
        
        insert_pos = content.find('\n', import_end) + 1
        new_content = content[:insert_pos] + local_rpc_config + content[insert_pos:]
        
        # Write updated content
        with open(deploy_script, 'w') as f:
            f.write(new_content)
        
        print(f"✅ Updated deploy_contracts.py to use local RPC: {LOCAL_RPC_URL}")
        return True
        
    except Exception as e:
        print(f"❌ Failed to update deploy_contracts.py: {e}")
        return False

def show_status():
    """Show the current status of Stellar containers."""
    print("📊 Stellar RPC Node Status")
    print("=" * 50)
    
    for network, config in NETWORK_CONFIGS.items():
        container_name = config["container_name"]
        status = get_container_status(container_name)
        
        if status == "not_found":
            print(f"❌ {network.upper()}: Container not found")
        elif "Up" in status:
            print(f"✅ {network.upper()}: Container running ({status})")
            
            # Check health
            health = get_node_health()
            sync = check_sync_status()
            
            if health["status"] == "healthy":
                print(f"   🟢 Health: Healthy")
            else:
                print(f"   🔴 Health: {health['status']}")
            
            if sync.get("isSynced", False):
                print(f"   🟢 Sync: Synced (Ledger: {sync.get('ledger', 'Unknown')})")
            else:
                print(f"   🟡 Sync: Syncing...")
        else:
            print(f"⏸️  {network.upper()}: Container stopped ({status})")
    
    print(f"\n🌐 Local RPC URL: {LOCAL_RPC_URL}")

def main():
    """Main function."""
    parser = argparse.ArgumentParser(description="Setup local Stellar RPC node")
    parser.add_argument("--network", choices=["mainnet", "testnet"], 
                       help="Network to setup")
    parser.add_argument("--stop", action="store_true",
                       help="Stop all Stellar containers")
    parser.add_argument("--status", action="store_true", 
                       help="Show container status")
    parser.add_argument("--monitor", action="store_true",
                       help="Monitor sync progress")
    parser.add_argument("--update-deploy", action="store_true",
                       help="Update deploy_contracts.py for local RPC")
    
    args = parser.parse_args()
    
    print("🚀 Local Stellar RPC Node Setup")
    print("=" * 50)
    print("📚 Official Documentation:")
    print("   • Docker Image: https://hub.docker.com/r/stellar/soroban-rpc")
    print("   • RPC Docs: https://developers.stellar.org/docs/data/apis/rpc/")
    print("   • GitHub: https://github.com/stellar/stellar-rpc")
    print()
    
    if args.status:
        show_status()
        return
    
    if args.stop:
        stop_stellar_container()
        return
    
    if args.monitor:
        monitor_sync_progress()
        return
    
    if args.update_deploy:
        update_deploy_script_rpc_url()
        return
    
    if not args.network:
        print("❌ Please specify --network mainnet or --network testnet")
        parser.print_help()
        return
    
    # Setup sequence
    network = args.network
    
    print(f"🎯 Setting up {network} Stellar RPC node...")
    
    # Step 1: Check Docker
    if not check_docker_installation():
        return
    
    # Step 2: Check/pull image
    if not check_image_exists(DOCKER_IMAGE):
        if not pull_docker_image(DOCKER_IMAGE):
            return
    
    # Step 3: Create directories
    if not create_required_directories():
        return
    
    # Step 4: Start container
    if not start_stellar_container(network):
        return
    
    # Step 5: Update deploy script
    if args.update_deploy or input("\nUpdate deploy_contracts.py for local RPC? (y/N): ").lower() == 'y':
        update_deploy_script_rpc_url()
    
    # Step 6: Monitor sync
    if input("\nMonitor sync progress? (Y/n): ").lower() != 'n':
        monitor_sync_progress()
    
    print(f"\n✅ Setup complete!")
    print(f"   Local RPC URL: {LOCAL_RPC_URL}")
    print(f"   Use: uv run deploy_contracts.py --deployer-acct YOUR_ACCOUNT --network {network}")

if __name__ == "__main__":
    main()
