# This file was generated by stellar_contract_bindings v0.5.0b0 and stellar_sdk v13.2.1.

from __future__ import annotations

from enum import IntEnum, Enum
from typing import Dict, List, Tuple, Optional, Union

from stellar_sdk import scval, xdr, Address, MuxedAccount, Keypair
from stellar_sdk.contract import AssembledTransaction, ContractClient
from stellar_sdk.contract import AssembledTransactionAsync, ContractClientAsync

NULL_ACCOUNT = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF"


class NetworkKind(Enum):
    Testnet = "Testnet"
    Mainnet = "Mainnet"


class Network:
    def __init__(
        self,
        kind: NetworkKind,
    ):
        self.kind = kind

    def to_scval(self) -> xdr.SCVal:
        if self.kind == NetworkKind.Testnet:
            return scval.to_enum(self.kind.name, None)
        if self.kind == NetworkKind.Mainnet:
            return scval.to_enum(self.kind.name, None)
        raise ValueError(f"Invalid kind: {self.kind}")

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_enum(val)
        kind = NetworkKind(elements[0])
        if kind == NetworkKind.Testnet:
            return cls(kind)
        if kind == NetworkKind.Mainnet:
            return cls(kind)
        raise ValueError(f"Invalid kind: {kind}")

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Network):
            return NotImplemented
        if self.kind != other.kind:
            return False
        return True

    def __hash__(self) -> int:
        return hash(self.kind)


class DataKeyKind(Enum):
    Admin = "Admin"
    AdminList = "AdminList"
    ContractId = "ContractId"
    Registry = "Registry"


class DataKey:
    def __init__(
        self,
        kind: DataKeyKind,
        contract_id: Optional[Tuple[bytes, Network]] = None,
        registry: Optional[Network] = None,
    ):
        self.kind = kind
        self.contract_id = contract_id
        self.registry = registry

    def to_scval(self) -> xdr.SCVal:
        if self.kind == DataKeyKind.Admin:
            return scval.to_enum(self.kind.name, None)
        if self.kind == DataKeyKind.AdminList:
            return scval.to_enum(self.kind.name, None)
        if self.kind == DataKeyKind.ContractId:
            assert isinstance(self.contract_id, tuple)
            return scval.to_enum(
                self.kind.name,
                [scval.to_string(self.contract_id[0]), self.contract_id[1].to_scval()],
            )
        if self.kind == DataKeyKind.Registry:
            assert self.registry is not None
            return scval.to_enum(self.kind.name, self.registry.to_scval())
        raise ValueError(f"Invalid kind: {self.kind}")

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_enum(val)
        kind = DataKeyKind(elements[0])
        if kind == DataKeyKind.Admin:
            return cls(kind)
        if kind == DataKeyKind.AdminList:
            return cls(kind)
        if kind == DataKeyKind.ContractId:
            assert elements[1] is not None and isinstance(elements[1], list)
            return cls(
                kind,
                contract_id=(
                    scval.from_string(elements[1][0]),
                    Network.from_scval(elements[1][1]),
                ),
            )
        if kind == DataKeyKind.Registry:
            assert elements[1] is not None and isinstance(elements[1], xdr.SCVal)
            return cls(kind, registry=Network.from_scval(elements[1]))
        raise ValueError(f"Invalid kind: {kind}")

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, DataKey):
            return NotImplemented
        if self.kind != other.kind:
            return False
        if self.kind == DataKeyKind.ContractId:
            return self.contract_id == other.contract_id
        if self.kind == DataKeyKind.Registry:
            return self.registry == other.registry
        return True

    def __hash__(self) -> int:
        if self.kind == DataKeyKind.ContractId:
            return hash((self.kind, self.contract_id))
        if self.kind == DataKeyKind.Registry:
            return hash((self.kind, self.registry))
        return hash(self.kind)


class ContractEntry:
    contract_id: Address
    name: bytes

    def __init__(self, contract_id: Union[Address, str], name: bytes):
        self.contract_id = contract_id
        self.name = name

    def to_scval(self) -> xdr.SCVal:
        return scval.to_struct(
            {
                "contract_id": scval.to_address(self.contract_id),
                "name": scval.to_string(self.name),
            }
        )

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_struct(val)
        return cls(
            scval.from_address(elements["contract_id"]),
            scval.from_string(elements["name"]),
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, ContractEntry):
            return NotImplemented
        return self.contract_id == other.contract_id and self.name == other.name

    def __hash__(self) -> int:
        return hash((self.contract_id, self.name))


class RegistryEvent:
    contract_id: Address
    name: bytes
    network: Network

    def __init__(self, contract_id: Union[Address, str], name: bytes, network: Network):
        self.contract_id = contract_id
        self.name = name
        self.network = network

    def to_scval(self) -> xdr.SCVal:
        return scval.to_struct(
            {
                "contract_id": scval.to_address(self.contract_id),
                "name": scval.to_string(self.name),
                "network": self.network.to_scval(),
            }
        )

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_struct(val)
        return cls(
            scval.from_address(elements["contract_id"]),
            scval.from_string(elements["name"]),
            Network.from_scval(elements["network"]),
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, RegistryEvent):
            return NotImplemented
        return (
            self.contract_id == other.contract_id
            and self.name == other.name
            and self.network == other.network
        )

    def __hash__(self) -> int:
        return hash((self.contract_id, self.name, self.network))


class RemoveEvent:
    name: bytes
    network: Network

    def __init__(self, name: bytes, network: Network):
        self.name = name
        self.network = network

    def to_scval(self) -> xdr.SCVal:
        return scval.to_struct(
            {"name": scval.to_string(self.name), "network": self.network.to_scval()}
        )

    @classmethod
    def from_scval(cls, val: xdr.SCVal):
        elements = scval.from_struct(val)
        return cls(
            scval.from_string(elements["name"]), Network.from_scval(elements["network"])
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, RemoveEvent):
            return NotImplemented
        return self.name == other.name and self.network == other.network

    def __hash__(self) -> int:
        return hash((self.name, self.network))


class Client(ContractClient):
    def set_contract_id(
        self,
        caller: Union[Address, str],
        name: bytes,
        network: Network,
        contract_id: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[None]:
        """Set or update a contract ID in the registry. Admin only."""
        return self.invoke(
            "set_contract_id",
            [
                scval.to_address(caller),
                scval.to_string(name),
                network.to_scval(),
                scval.to_address(contract_id),
            ],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def remove_contract_id(
        self,
        caller: Union[Address, str],
        name: bytes,
        network: Network,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[None]:
        """Remove a contract ID from the registry. Admin only."""
        return self.invoke(
            "remove_contract_id",
            [scval.to_address(caller), scval.to_string(name), network.to_scval()],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def get_contract_id(
        self,
        name: bytes,
        network: Network,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[Address]:
        """Get a contract ID by name and network. Panics if not found."""
        return self.invoke(
            "get_contract_id",
            [scval.to_string(name), network.to_scval()],
            parse_result_xdr_fn=lambda v: scval.from_address(v),
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def has_contract_id(
        self,
        name: bytes,
        network: Network,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[bool]:
        """Check if a contract ID is registered."""
        return self.invoke(
            "has_contract_id",
            [scval.to_string(name), network.to_scval()],
            parse_result_xdr_fn=lambda v: scval.from_bool(v),
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def get_all_contracts(
        self,
        network: Network,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[List[ContractEntry]]:
        """Get all registered contracts for a network."""
        return self.invoke(
            "get_all_contracts",
            [network.to_scval()],
            parse_result_xdr_fn=lambda v: [
                ContractEntry.from_scval(e) for e in scval.from_vec(v)
            ],
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def add_admin(
        self,
        caller: Union[Address, str],
        new_admin: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[None]:
        return self.invoke(
            "add_admin",
            [scval.to_address(caller), scval.to_address(new_admin)],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def remove_admin(
        self,
        caller: Union[Address, str],
        admin_to_remove: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[None]:
        return self.invoke(
            "remove_admin",
            [scval.to_address(caller), scval.to_address(admin_to_remove)],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def is_admin(
        self,
        address: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[bool]:
        return self.invoke(
            "is_admin",
            [scval.to_address(address)],
            parse_result_xdr_fn=lambda v: scval.from_bool(v),
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    def get_admin_list(
        self,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransaction[List[Address]]:
        return self.invoke(
            "get_admin_list",
            [],
            parse_result_xdr_fn=lambda v: [
                scval.from_address(e) for e in scval.from_vec(v)
            ],
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )


class ClientAsync(ContractClientAsync):
    async def set_contract_id(
        self,
        caller: Union[Address, str],
        name: bytes,
        network: Network,
        contract_id: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[None]:
        """Set or update a contract ID in the registry. Admin only."""
        return await self.invoke(
            "set_contract_id",
            [
                scval.to_address(caller),
                scval.to_string(name),
                network.to_scval(),
                scval.to_address(contract_id),
            ],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def remove_contract_id(
        self,
        caller: Union[Address, str],
        name: bytes,
        network: Network,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[None]:
        """Remove a contract ID from the registry. Admin only."""
        return await self.invoke(
            "remove_contract_id",
            [scval.to_address(caller), scval.to_string(name), network.to_scval()],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def get_contract_id(
        self,
        name: bytes,
        network: Network,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[Address]:
        """Get a contract ID by name and network. Panics if not found."""
        return await self.invoke(
            "get_contract_id",
            [scval.to_string(name), network.to_scval()],
            parse_result_xdr_fn=lambda v: scval.from_address(v),
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def has_contract_id(
        self,
        name: bytes,
        network: Network,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[bool]:
        """Check if a contract ID is registered."""
        return await self.invoke(
            "has_contract_id",
            [scval.to_string(name), network.to_scval()],
            parse_result_xdr_fn=lambda v: scval.from_bool(v),
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def get_all_contracts(
        self,
        network: Network,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[List[ContractEntry]]:
        """Get all registered contracts for a network."""
        return await self.invoke(
            "get_all_contracts",
            [network.to_scval()],
            parse_result_xdr_fn=lambda v: [
                ContractEntry.from_scval(e) for e in scval.from_vec(v)
            ],
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def add_admin(
        self,
        caller: Union[Address, str],
        new_admin: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[None]:
        return await self.invoke(
            "add_admin",
            [scval.to_address(caller), scval.to_address(new_admin)],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def remove_admin(
        self,
        caller: Union[Address, str],
        admin_to_remove: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[None]:
        return await self.invoke(
            "remove_admin",
            [scval.to_address(caller), scval.to_address(admin_to_remove)],
            parse_result_xdr_fn=lambda _: None,
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def is_admin(
        self,
        address: Union[Address, str],
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[bool]:
        return await self.invoke(
            "is_admin",
            [scval.to_address(address)],
            parse_result_xdr_fn=lambda v: scval.from_bool(v),
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )

    async def get_admin_list(
        self,
        source: Union[str, MuxedAccount] = NULL_ACCOUNT,
        signer: Optional[Keypair] = None,
        base_fee: int = 100,
        transaction_timeout: int = 300,
        submit_timeout: int = 30,
        simulate: bool = True,
        restore: bool = True,
    ) -> AssembledTransactionAsync[List[Address]]:
        return await self.invoke(
            "get_admin_list",
            [],
            parse_result_xdr_fn=lambda v: [
                scval.from_address(e) for e in scval.from_vec(v)
            ],
            source=source,
            signer=signer,
            base_fee=base_fee,
            transaction_timeout=transaction_timeout,
            submit_timeout=submit_timeout,
            simulate=simulate,
            restore=restore,
        )
